main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.welcome_view, name='welcome'),
    path('success/', views.success_view, name='success'),
    path('check/', views.check_id, name='check'),
    path('home/', views.home_view, name='home'),
    path('home/<int:pk>/', views.status_view, name='status'),
    path('home/fakulty/<int:pk>/', views.fakulty_view, name='fakulty'),
    path('update/<int:pk>/', views.update_view, name='update'),
    path('print/<int:pk>/', views.print_view, name='print'),
    path('list/', views.lists_view, name='lists'),
]

turar_joy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.conf.urls.static import static
from main.views import none_page

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('account.urls')),
    path('', include('main.urls')),
    path('<str:name>/', none_page),
]

handler404 = 'main.views.handling_404'

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models


class Faculties(models.Model):
    name = models.CharField(max_length=200, verbose_name='Fakultet ismi')  # Translation
    link_name = models.CharField(max_length=200, verbose_name='fakultet link')

    def __str__(self):
        return self.name


class Status(models.Model):
    name = models.CharField(max_length=20, verbose_name='Status')

    def __str__(self):
        return self.name


class Application(models.Model):
    full_name = models.CharField(max_length=200, verbose_name='F.I.O.')
    birthday = models.DateField(verbose_name="Tug'ilgan kun")
    gender = models.CharField(max_length=10, verbose_name='Jinsi')
    email = models.EmailField(verbose_name='Email', null=True, blank=True)
    phone_number = models.CharField(max_length=50, verbose_name='Telefon nomer')

    faculty = models.ForeignKey(Faculties, verbose_name='Fakultet', on_delete=models.CASCADE, null=True, blank=True)
    course = models.CharField(max_length=20, verbose_name='Kurs', null=True, blank=True)
    image = models.ImageField(upload_to="./image/", verbose_name='Image')
    create_at = models.DateTimeField(auto_now_add=True, verbose_name='Ariza vaqti')

    # ijtimoiy holati
    pasport = models.FileField(upload_to='./pasport/', verbose_name='Passport nusxasi', null=True, blank=True)
    i_va_ii = models.FileField(upload_to='./i_va_ii/', verbose_name='I va II guruh nogiron', null=True, blank=True)
    temir_daftar = models.FileField(upload_to='./temir_daftar/', verbose_name='Temir daftar', null=True, blank=True)
    yetim = models.FileField(upload_to='./yetim/', verbose_name='Yetim', null=True, blank=True)
    yoshlar_daftar = models.FileField(upload_to='./yoshlar/', verbose_name='Yoshlar daftari', null=True, blank=True)
    oila_i_va_ii = models.FileField(upload_to='./oilada_i_va_ii/', verbose_name='Oilasida 1 va 2', null=True, blank=True)
    boshqa = models.FileField(upload_to='./boshqa/', verbose_name='Boshqa imtiyoz', null=True, blank=True)

    status = models.ForeignKey(Status, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='Status')
    commit = models.TextField(verbose_name='Sababi', null=True, blank=True)

    class Meta:
        ordering = ['create_at']

    def __str__(self):
        return self.full_name

main/views.py
from django.shortcuts import render, redirect
from .models import Faculties, Application, Status
from django.contrib import messages
from django.contrib.auth.decorators import login_required


def welcome_view(request):
    faculties = Faculties.objects.all()
    if request.method == 'POST':
        faculty = Faculties.objects.get(link_name=request.POST.get('fakultet'))
        application = Application.objects.create(full_name=request.POST.get('name'),
                                                 birthday=request.POST.get('birthday'),
                                                 gender=request.POST.get('gender'),
                                                 email=request.POST.get('email'),
                                                 phone_number=request.POST.get('number'),
                                                 faculty=faculty,
                                                 course=request.POST.get('kurs'),
                                                 image=request.FILES.get('image'),
                                                 pasport=request.FILES.get('pasport'),
                                                 i_va_ii=request.FILES.get('nogiron'),
                                                 temir_daftar=request.FILES.get('temir'),
                                                 yetim=request.FILES.get('yetim'),
                                                 yoshlar_daftar=request.FILES.get('yoshlar_daftar'),
                                                 oila_i_va_ii=request.FILES.get('oila_i_va_ii'),
                                                 boshqa=request.FILES.get('boshqa'),
                                                 status=Status.objects.get(pk=1)
                                                 )
        application.save()
        request.session['ariza'] = {'name': application.full_name, 'id': application.id}
        return redirect('main:success')
    content = {
        'faculties': faculties,
    }
    return render(request, 'main/index.html', content)


def success_view(request):
    return render(request, 'main/success.html')


def check_id(request):
    if request.method == 'POST':
        application_id = request.POST.get('id')
        try:
            application = Application.objects.get(id=application_id)
        except:
            return render(request, 'main/check.html', {'message': "Bunday ariza ro'yhatdan o'tmagan."})
        return render(request, 'main/check.html', {'application': application})
    else:
        return render(request, 'main/check.html')


@login_required(login_url='account:login')
def home_view(request):
    faculties = Faculties.objects.all()
    applications = Application.objects.all()
    status = Status.objects.all()
    content = {
        'faculties': faculties,
        'applications': applications,
        'hammasi': len(applications),
        'qabul': len(Application.objects.filter(status_id=2)),
        'radetildi': len(Application.objects.filter(status_id=3)),
        'korilmaganlar': len(Application.objects.filter(status_id=1)),
    }
    return render(request, 'main/list.html', content)


@login_required(login_url='account:login')
def update_view(request, pk):
    application = Application.objects.get(pk=pk)
    status = Status.objects.all()
    if request.method == 'POST':
        statu = Status.objects.get(pk=request.POST.get('status'))
        commit = request.POST.get('comment')
        print(statu)
        application.status = statu
        application.commit = commit
        application.save()
        return redirect('main:home')
    content = {
        'application': application,
        'status': status,
    }
    return render(request, 'main/update.html', content)


@login_required(login_url='account:login')
def status_view(request, pk):
    status = Status.objects.get(pk=pk)
    applications = Application.objects.filter(status=status)
    faculties = Faculties.objects.all()
    content = {
        'faculties': faculties,
        'applications': applications,
        'hammasi': len(Application.objects.all()),
        'qabul': len(Application.objects.filter(status_id=2)),
        'radetildi': len(Application.objects.filter(status_id=3)),
        'korilmaganlar': len(Application.objects.filter(status_id=1)),
        'status': status,
    }
    return render(request, 'main/list.html', content)


@login_required(login_url='account:login')
def fakulty_view(request, pk):
    faculty = Faculties.objects.get(pk=pk)
    applications = Application.objects.filter(faculty=faculty)
    faculties = Faculties.objects.all()
    content = {
        'faculties': faculties,
        'applications': applications,
        'hammasi': len(Application.objects.all()),
        'qabul': len(Application.objects.filter(status_id=2)),
        'radetildi': len(Application.objects.filter(status_id=3)),
        'korilmaganlar': len(Application.objects.filter(status_id=1)),
        'fakulty': faculty,
    }
    return render(request, 'main/list.html', content)


@login_required(login_url='account:login')
def print_view(request, pk):
    if pk == 1:
        applications = Application.objects.all()
    else:
        applications = Application.objects.filter(pk=pk)
    content = {
        'applications': applications,
        'status': pk,
    }
    return render(request, 'main/print.html', content)


def lists_view(request):
    return render(request, 'main/home.html')


def handling_404(request, exception):
    return render(request, 'handler404.html', {})


def none_page(request, name):
    return render(request, 'main/none_page.html', {'name': name})

templates/main/check.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}

    <div class="container-sm" style="width: 80%;">
        {% if application %}
            <div class="form-control">
                <ul class="nav nav-pills nav-fill">
                    <li class="nav-item btn btn-outline-primary" style="margin: 10px;">
                        <a class="nav-link" aria-current="page" href="{% url 'main:welcome' %}">Ariza topshirish</a>
                    </li>
                    <li class="nav-item btn btn-outline-primary" style="margin: 10px;">
                        <a class="nav-link" href="{% url 'main:check' %}">Arizani tekshirish</a>
                    </li>
                </ul>
                {% if application.status.id == 2 %}
                    <div class="alert alert-success container-sm" role="alert">
                        <h4 class="alert-heading">
                            {{ application.full_name }} sizning arizangiz: Qabul qilindi.
                        </h4>
                        <p>
                            {{ application.commit }}
                        </p>
                        <hr>
                        {#                        <p class="mb-0">#}
                        {#                            Arizangiz natijasi bo'yicha <a href="tel:+998-91-234-44-90" style="text-decoration: none;">+998-91-234-44-90</a>#}
                        {#                            nomeri bilan bog'lanishingiz mumkin!#}
                        {#                        </p>#}
                    </div>
                {% elif application.status.id == 3 %}
                    <div class="alert alert-danger container-sm" role="alert">
                        <h4 class="alert-heading">
                            {{ application.full_name }} sizning arizangiz: Rad etildi.
                        </h4>
                        <p>
                            {{ application.commit }}
                        </p>
                        <hr>
                        {#                        <p class="mb-0">#}
                        {#                            Arizangiz natijasi bo'yicha <a href="tel:+998-91-234-44-90" style="text-decoration: none;">+998-91-234-44-90</a>#}
                        {#                            nomeri bilan bog'lanishingiz mumkin!#}
                        {#                        </p>#}
                    </div>
                {% else %}
                    <div class="alert alert-warning container-sm" role="alert">
                        <h4 class="alert-heading">
                            {{ application.full_name }} sizning arizangiz: Ko'rilgani yo'q.
                        </h4>
                        <p>
                            Tez orada Arizangiz ko'rib chiqiladi. ID raqamingiz bo'yicha keyinroq tekshirib ko'ring.
                        </p>
                        <hr>
                        {#                        <p class="mb-0">#}
                        {#                            Arizangiz natijasi bo'yicha <a href="tel:+998-91-234-44-90" style="text-decoration: none;">+998-91-234-44-90</a>#}
                        {#                            nomeri bilan bog'lanishingiz mumkin!#}
                        {#                        </p>#}
                    </div>
                {% endif %}
            </div>
        {% else %}
            <form action="" method="post" class="form-control" enctype="multipart/form-data">
                <ul class="nav nav-pills nav-fill">
                    <li class="nav-item btn btn-outline-primary" style="margin: 10px;">
                        <a class="nav-link" aria-current="page" href="{% url 'main:welcome' %}">Ariza topshirish</a>
                    </li>
                    <li class="nav-item btn btn-outline-primary" style="margin: 10px;">
                        <a class="nav-link" href="{% url 'main:check' %}">Arizani tekshirish</a>
                    </li>
                </ul>
                <hr>
                {% csrf_token %}
                <div class="mb-3">
                    {% if message %}
                    <div class="alert alert-warning alert-dismissible fade show" role="alert">
                        <strong>{{ message }}</strong>
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    {% endif %}

                    <label for="id" class="form-label h2" style="padding: 10px;">Ro'yhatga olingan tartib raqamingizni
                        kiriting:</label>

                    <input type="number" name="id" class="form-control" id="id" aria-describedby="idhelp"
                           placeholder="ID raqamingiz:" style="padding: 10px; margin: 10px;" required>
                    <div id="idhelp" class="form-text" style="padding: 5px 5px 5px 10px;">
                        Sizning arizangiz holatini bilish uchun ID raqamni kiriting
                    </div>
                </div>
                <button type="submit" class="btn btn-primary container">Tekshirish</button>
            </form>
        {% endif %}
    </div>
{% endblock %}

templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block list %}
    <div class="row border theme-colors">
        <div class="col-lg-2 border">
            <h3>TTJ Admin</h3>
        </div>
        <div class="col-lg-10 border">
            <h3>
                Toshkent Davlat Stomatologiya Instituti talabalarini Talabalar turar joyi bilan ta'minlash
            </h3>
        </div>
    </div>
{% endblock %}

templates/main/list.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static '/styles/main.css' %}">
    <link rel="stylesheet" href="{% static 'styles/icons/css/font-awesome.css' %}">
    <link rel="stylesheet" href="{% static 'styles/icons/css/font-awesome.min.css' %}">
    <script src="{% static 'scripts/jquery.js' %}"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet">
    <link rel="icon" href="{% static 'images/logotip.png' %}">
    <title>Talabalar turar joyi</title>
</head>
<body>
<style>
    .dropbtn {
        background-color: #4CAF50;
        color: white;
        padding: 16px;
        font-size: 16px;
        border: none;
        cursor: pointer;
    }

    .dropdown {
        position: relative;
        display: inline-block;
    }

    .dropdown-content {
        display: none;
        position: absolute;
        background-color: #f9f9f9;
        min-width: 160px;
        box-shadow: 0px 8px 16px 0px rgba(0, 0, 0, 0.2);
        z-index: 1;
    }

    .dropdown-content a {
        color: black;
        padding: 12px 16px;
        text-decoration: none;
        display: block;
    }

    .dropdown-content a:hover {
        background-color: #f1f1f1
    }

    .dropdown:hover .dropdown-content {
        display: block;
    }

    .dropdown:hover .dropbtn {
        background-color: #3e8e41;
    }
</style>
<div class="container mini-admin">
    <header id="header">
        <a href="{% url 'main:home' %}" style="color:#FFF;">
            <nav><img src="{% static 'images/logo-wide.png' %}" alt="alt"/>
                <p>TTJ Admin</p></nav>
        </a>
        <p class="title">
            <i class="fa fa-envelope"></i>
            Toshkent Davlat Stomatologiya Institutida tahsil olayotgan talabalarni talabalar turar joyiga online
            ro'yhatga olish
        </p>
    </header>
    <div class="main">
        <div class="content">
            <div class="left-bar">
                <ul class="data-sort">
                    <li class="data-sort-otdel">
                        <label for="radio02">
                            <a href="{% url 'main:home' %}">
                                Ro'yhatdan o'tganlar
                            </a>
                        </label>
                    </li>
                    <br>
                    <li class="data-sort-sotrudnik">
                        <label for="radio01">
                            <a href="{% url 'main:status' 2 %}">
                                TTJga qabul qilinganlar
                            </a>
                        </label>
                    </li>
                    <br/>
                    <li class="data-sort-today">
                        <label for="radio1">
                            <a href="{% url 'main:status' 3 %}">
                                Qabul qilinmaganlar
                            </a>
                        </label>
                    </li>
                </ul>
                <h3>Statistika:</h3>
                <ul class="main-stat">
                    <li>
                        <i class="fa fa-file-word-o"></i>
                        <p>Hamma</p>
                        <p>{{ hammasi }}</p>
                    </li>
                    <li><i class="fa fa-file-word-o"></i>
                        <p>Qabul qilinganlar</p>
                        <p>{{ qabul }}</p>
                    </li>
                    <li>
                        <i class="fa fa-file-word-o"></i>
                        <p>Rad etilganlar</p>
                        <p>{{ radetildi }}</p>
                    </li>
                    <li>
                        <i class="fa fa-file-word-o"></i>
                        <p>Ko'rilmaganlar</p>
                        <p>{{ korilmaganlar }}</p>
                    </li>


                </ul>
                <hr>
                <h3 style="text-align: center;">Pechat qilish</h3>
                <hr>
                <ul class="data-sort">
                    <li class="data-sort-otdel clprint">
                        <label for="radio02">
                            <a href="{% url 'main:print' 1 %}">
                                Ro'yhatdan o'tganlar
                                <i class="fa fa-print"></i>
                            </a>
                        </label>
                    </li>
                    <br>
                    <li class="data-sort-sotrudnik clprint">
                        <label for="radio01">
                            <a href="{% url 'main:print' 2 %}">
                                TTJga qabul qilinganlar
                                <i class="fa fa-print"></i>
                            </a>
                        </label>
                    </li>
                    <br/>
                    <li class="data-sort-today clprint">
                        <label for="radio1">
                            <a href="{% url 'main:print' 3 %}">
                                Qabul qilinmaganlar
                                <i class="fa fa-print"></i>
                            </a>
                        </label>
                    </li>
                </ul>

            </div>
            <div class="main-bar">
                <div class="welcome">
                    <p>
                        <a class="add-order-btn" href="/">
                            Ariza qo'shish
                        </a>
                    </p>
                    <div class="dropdown">
                        <button class="dropbtn">Fakultet</button>
                        <div class="dropdown-content">
                            {% for faculty in faculties %}
                                <a href="{% url 'main:fakulty' faculty.id %}">{{ faculty.name_uz }}</a>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="table">
                        <table id="customers" class="main-table">
                            <tr>
                                <th>id</th>
                                <th>F.I.O.</th>
                                <th>Tug'ilgan sana</th>
                                <th>Ariza vaqti</th>
                                <th>Jinsi</th>
                                <th>Telefon nomer</th>
                                <th>Fakultet</th>
                                <th>Kurs</th>
                                <th>Ariza holati</th>
                                <th><i class="fa fa-spin fa-gear"></i></th>
                            </tr>
                            {% for application in applications %}
                                <tr style="padding: 0; background: {% if application.status.id == 2 %} #c2f8b5; {% elif application.status.id == 3 %} #e5939a;{% endif %} border-bottom: 1px solid #f1e4e4;">
                                    <td class="td-id">
                                        <a href="{% url 'main:update' application.id %}">
                                            {{ application.id }}
                                        </a>
                                    </td>
                                    <td>
                                        <a href="{% url 'main:update' application.id %}">
                                            {{ application.full_name }}
                                        </a>
                                    </td>
                                    <td class="td-doc_date">
                                        {{ application.birthday|date:"d.m.Y" }}
                                    </td>
                                    <td>
                                        {{ application.create_at|time:"H:i" }}
                                        | {{ application.create_at|date:"d.m.Y" }}
                                    </td>
                                    <td class="td-doc_date">
                                        {{ application.gender }}
                                    </td>
                                    <td class="td-doc_date">
                                        <a href="te:{{ application.phone_number }}">
                                            {{ application.phone_number }}
                                        </a>
                                    </td>

                                    <td class="td-doc_date">
                                        {{ application.faculty.name_uz }}
                                    </td>
                                    <td class="td-tipconcart">
                                        {{ application.course }}
                                    </td>
                                    <td class="td-tipconcart">
                                        <b>{{ application.status }}</b>
                                    </td>
                                    {#                                    {% if application.i_va_ii %}#}
                                    {#                                        <td class="td-tip_doc">#}
                                    {#                                            <a href="{{ application.i_va_ii.url }}" target="_blank">#}
                                    {#                                                <img src="{% static 'images/down1.png' %}" width="40" alt="">#}
                                    {#                                            </a>#}
                                    {#                                        </td>#}
                                    {#                                    {% else %}#}
                                    {#                                        <td class="td-tip_doc">#}
                                    {#                                            <a href="#" target="_blank">#}
                                    {##}
                                    {#                                            </a>#}
                                    {#                                        </td>#}
                                    {#                                    {% endif %}#}
                                    {#                                    {% if application.temir_daftar %}#}
                                    {#                                        <td class="td-tip_doc">#}
                                    {#                                            <a href="{{ application.temir_daftar.url }}" target="_blank">#}
                                    {#                                                <img src="{% static 'images/down2.png' %}" width="40" alt="">#}
                                    {#                                            </a>#}
                                    {#                                        </td>#}
                                    {#                                    {% else %}#}
                                    {#                                        <td class="td-tip_doc">#}
                                    {#                                            <a href="#" target="_blank">#}
                                    {##}
                                    {#                                            </a>#}
                                    {#                                        </td>#}
                                    {#                                    {% endif %}#}
                                    {#                                    {% if application.yetim %}#}
                                    {#                                        <td class="td-tip_doc">#}
                                    {#                                            <a href="{{ application.yetim.url }}" target="_blank">#}
                                    {#                                                <img src="{% static 'images/down3.png' %}" width="40" alt="">#}
                                    {#                                            </a>#}
                                    {#                                        </td>#}
                                    {#                                    {% else %}#}
                                    {#                                        <td class="td-tip_doc">#}
                                    {#                                            <a href="#" target="_blank">#}
                                    {##}
                                    {#                                            </a>#}
                                    {#                                        </td>#}
                                    {#                                    {% endif %}#}
                                    <td class="">
                                        <a href="{% url 'main:update' application.id %}">
                                            <i class="order-editor fa fa-edit"
                                               style="padding: 10px; font-size: 1.5em;"></i>
                                        </a>
                                    </td>
                                </tr>
                            {% endfor %}
                        </table>
                    </div>
                </div>
                <br>
            </div>
        </div>
    </div>

</div>
</body>

<script type="text/JavaScript" src="{% static 'scripts/main.js' %}"></script>
</html>

templates/main/none_page.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block content %}
    <div class="container-sm" style="height: 200px;">
        <form action="" method="get" class="form-control" enctype="multipart/form-data" style="padding-bottom: 20px; height: 600px;">
            <ul class="nav nav-pills nav-fill">
                <li class="nav-item btn btn-outline-primary" style="margin: 10px;">
                    <a class="nav-link" aria-current="page" href="">Ariza topshirish</a>
                </li>
                <li class="nav-item btn btn-outline-primary" style="margin: 10px;">
                    <a class="nav-link" href="{% url 'main:check' %}">Arizani tekshirish</a>
                </li>
            </ul>
            <hr>
            <h2 class="p-2" style="text-align: center;">
                {{ name }}: Not found...
            </h2>
        </form>
        <h3 style="padding: 30px;"></h3>
    </div>
{% endblock %}

templates/main/success.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block content %}
    <div class="container-sm">
        <div class="form-control">
            <ul class="nav nav-pills nav-fill">
                <li class="nav-item btn btn-outline-primary" style="margin: 10px;">
                    <a class="nav-link" aria-current="page" href="{% url 'main:welcome' %}">Ariza topshirish</a>
                </li>

                <li class="nav-item btn btn-outline-primary" style="margin: 10px;">
                    <a class="nav-link" href="{% url 'main:check' %}">Arizani tekshirish</a>
                </li>
            </ul>
            <hr>

            <div class="alert alert-success container-sm" role="alert">
                <h4 class="alert-heading">
                    {{ request.session.ariza.name }} Arizangiz yuborildi.
                </h4>
                <p>
                    Sizning Arizangizni ID raqami <b>{{ request.session.ariza.id }}</b> arizangizni holatini shu ID raqam
                    bilan tekshirishingiz mumkin.
                </p>
{#                <hr>#}
{#                <p class="mb-0">#}
{#                    Arizangiz natijasi bo'yicha <a href="tel:+998-91-234-44-90" style="text-decoration: none;">+998-91-234-44-90</a>#}
{#                    nomeri bilan bog'lanishingiz mumkin!#}
{#                </p>#}
            </div>
        </div>
       
    </div>

{% endblock %}